### ISSUE TITLE
Still failing to build due to FMT errors

### ISSUE THREAD

**Issue by DarkShadow44** [bartoszek/AUR-luxcorerender#15]
Sorry, it's still not working for me: [luxcorerender.log](https://github.com/bartoszek/AUR-luxcorerender/files/13652673/luxcorerender.log)

Just did a `git clone` and `makepkg -fis` and that's the result. It still seems to use fmt10.

**Comment by howetuft** [comment]
Hello,
I can reproduce (in a clean chroot) but I cannot fix yet. I keep searching.

**Comment by DarkShadow44** [comment]
Fixed with latest release, thanks!
