### ISSUE TITLE
Reduce package size

### ISSUE THREAD

**Issue by JayFoxRox** [bartoszek/AUR-luxcorerender#2]
I'm short on disk space, and I realized that luxcorerender takes more than 2GB in space, with each binary being about 300MB. After stripping, each binary is 10-20MB for a total of less than 100MB for all of them. When also stripping the static libraries the package is about 150MB in total.

I'm not sure if an unstripped binary is really beneficial for most people either, so I feel like these should be stripped by default.

However, I don't know how to solve this (but I imagine you can follow what other popular packages do). Unfortunately, `cmake -DCMAKE_BUILD_TYPE=Release` is not enough (but will likely lead to better optimizations / performance); so more flags would have to be added (See [this](https://stackoverflow.com/questions/38675403/how-to-config-cmake-for-strip-file)). An alternative approach would be to manually run `strip` for those binaries.

*This also applies to some of your other packages, in particular, I can reduce size by half, in https://github.com/bartoszek/AUR-oidn by stripping the binary / I probably want an explicit release build to benefit from most optimizations.*

**Comment by bartoszek** [comment]
Please check your `makepkg` configuration (`/etc/makepkg.conf`) if you are building in your running system. It should contains line specifying build options (`OPTIONS=(strip docs !libtool !staticlibs emptydirs zipman purge !debug`). I'm strongly suggesting building every package in [clean chroot](https://wiki.archlinux.org/index.php/DeveloperWiki:Building_in_a_clean_chroot) to keep consistency across builds (simple automation script [CCM](https://github.com/graysky2/clean-chroot-manager)). My system shows content of `oidn` and `luxcorerender` packages stripped and quite small.
* oidn 
```
35M	usr/lib/libOpenImageDenoise.so.0.8.2
usr/lib/libOpenImageDenoise.so.0.8.2: ELF 64-bit LSB shared object, x86-64, version 1 (GNU/Linux), dynamically linked, BuildID[sha1]=bc68b406ed49131817e673b8ab4d833f6ccc170d, stripped
```
* luxcorerender
```
18M	/usr/bin/luxcoreui
/usr/bin/luxcoreui: ELF 64-bit LSB pie executable, x86-64, version 1 (GNU/Linux), dynamically linked, interpreter /lib64/ld-linux-x86-64.so.2, for GNU/Linux 3.2.0, BuildID[sha1]=8bf298b25ff883666e13f3cbacb50fcc22d12135, stripped
```

**Comment by JayFoxRox** [comment]
My local configuration is indeed non-default:

```
OPTIONS=(!strip docs !libtool !staticlibs emptydirs zipman purge !upx debug)
```

I've probably changed it temporarily and forgot to change it back, or it was masked before I switched from `yaourt` to `pikaur`.

Thanks for the pointers - I'll try changing my global configuration.

**Comment by bartoszek** [comment]
@JayFoxRox If I may suggest something, you can create `/etc/makepkg.conf.debug` with altered `OPTIONS` and pass it as arg to `makepkg` whenever you intent to build debug package :thinking:
