### ISSUE TITLE
Update to AUR

### ISSUE THREAD

**Issue by DarkShadow44** [bartoszek/AUR-luxcorerender#7]
Can you please push the latest version to the AUR?

**Comment by bartoszek** [comment]
Could you be more specific, there wasn't any new tag since `v2.5`, which commit you consider ready to package? Or are you looking for backporting some commits from current master to luxcore:2.5? 

I wasn't really using luxcore lately, sorry for lagging behind on current development.

**Comment by DarkShadow44** [comment]
Hi, it currently doesn't build from the AUR. commit 1c78a51240d22c58ac2e99c0bb87e577c8dc81f4 is needed for that to work.
