### ISSUE TITLE
OpenEXR/half.h not found

### ISSUE THREAD

**Issue by kebugcheckex** [bartoszek/AUR-luxcorerender#8]
Also reported in LuxCoreRender/LuxCore: https://github.com/LuxCoreRender/LuxCore/issues/551

Workaround is to replace all occurrences of `#include <OpenEXR/half.h>` to `#include <Imath/half.h>` after properly setting `OpenEXR_Imath_INCLUDE_DIR`
```
CMAKE_FLAGS+=("-DOpenEXR_Imath_INCLUDE_DIR=/usr/include/Imath")
```
I can prepare a patch if this is a real issue.

**Comment by bartoszek** [comment]
Yep, already had this covered, but it doesn't resolve all issues when building against `openexr:3`. Looks like some shit needs to be reimplemented or at least retouch to work with the latest version of `openexr` :feelsgood: 

_If can't figure out a patch for it, will push a non-conflicting version of `openexr2` package to the AUR and switch `luxcorerender` deps to it._
